/*
 * opentmlib.hpp
 * This file is part of an open-source test and measurement I/O library.
 * See documentation for details.
 *
 * Copyright (C) 2011, Stefan Kopp, Gechingen, Germany
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * The GNU General Public License is available at
 * http://www.gnu.org/copyleft/gpl.html.
 */

enum OPENTMLIB_ERRORS
{

	/* General error codes */
	OPENTMLIB_ERROR_BAD_ATTRIBUTE,
	OPENTMLIB_ERROR_BAD_ATTRIBUTE_VALUE,
	OPENTMLIB_ERROR_BAD_OPERATION,
	OPENTMLIB_ERROR_BAD_OPERATION_VALUE,
	OPENTMLIB_ERROR_TIMEOUT,
	OPENTMLIB_ERROR_MEMORY_ALLOCATION,
	OPENTMLIB_ERROR_BUFFER_OVERFLOW,
	OPENTMLIB_ERROR_BINBLOCK_HEADER,
	OPENTMLIB_ERROR_BINBLOCK_SIZE,

	/* Error codes specific to socket driver */
	OPENTMLIB_ERROR_SOCKET_REQUEST_TOO_MUCH,
	OPENTMLIB_ERROR_SOCKET_CREATE,
	OPENTMLIB_ERROR_SOCKET_CONNECT,
	OPENTMLIB_ERROR_SOCKET_CLOSE,

	/* Error codes specific to USBTMC driver */
	OPENTMLIB_ERROR_USBTMC_OPEN,
	OPENTMLIB_ERROR_USBTMC_WRITE,
	OPENTMLIB_ERROR_USBTMC_READ,
	OPENTMLIB_ERROR_USBTMC_DEVICE_NOT_FOUND,
	OPENTMLIB_ERROR_USBTMC_MINOR_OUT_OF_RANGE,

	/* Error codes specific to VXI11 driver */
	OPENTMLIB_ERROR_VXI11_RPC,
	OPENTMLIB_ERROR_VXI11_CONNECTION,
	OPENTMLIB_ERROR_VXI11_ABORT_CONNECTION,
	OPENTMLIB_ERROR_VXI11_LINK,
	OPENTMLIB_ERROR_VXI11_READ,
	OPENTMLIB_ERROR_VXI11_WRITE,
	OPENTMLIB_ERROR_VXI11_READ_STB,
	OPENTMLIB_ERROR_VXI11_OPERATION,
	OPENTMLIB_ERROR_VXI11_OP_UNSUPPORTED,
	OPENTMLIB_ERROR_VXI11_MSG_SIZE,

};

enum OPENTMLIB_ATTRIBUTES
{

	/* General attributes */
	OPENTMLIB_ATTRIBUTE_TIMEOUT,
	OPENTMLIB_ATTRIBUTE_TERM_CHAR_ENABLE,
	OPENTMLIB_ATTRIBUTE_TERM_CHARACTER,
	OPENTMLIB_ATTRIBUTE_STATUS_BYTE,
	OPENTMLIB_ATTRIBUTE_SET_END_INDICATOR,

	/* Attributes specific to USBTMC driver */
	OPENTMLIB_ATTRIBUTE_USBTMC_INTERFACE_CAPS,
	OPENTMLIB_ATTRIBUTE_USBTMC_DEVICE_CAPS,
	OPENTMLIB_ATTRIBUTE_USBTMC_488_INTERFACE_CAPS,
	OPENTMLIB_ATTRIBUTE_USBTMC_488_DEVICE_CAPS,

	/* Attributes specific to socket driver */
	OPENTMLIB_ATTRIBUTE_SOCKET_BUFFER_SIZE,

	/* Attributes specific to VXI-11 */
	OPENTMLIB_ATTRIBUTE_VXI11_MAXRECVSIZE,
	OPENTMLIB_ATTRIBUTE_VXI11_WAIT_LOCK,
	OPENTMLIB_ATTRIBUTE_VXI11_LAST_ERROR,

};

enum OPENTMLIB_OPERATION_CODES
{
	/* General operation codes */
	OPENTMLIB_OPERATION_TRIGGER,
	OPENTMLIB_OPERATION_CLEAR,
	OPENTMLIB_OPERATION_REMOTE,
	OPENTMLIB_OPERATION_LOCAL,
	OPENTMLIB_OPERATION_LOCK,
	OPENTMLIB_OPERATION_UNLOCK,
	OPENTMLIB_OPERATION_ENABLE_SRQ,



	/* Operation codes specific to VXI-11 */
	OPENTMLIB_OPERATION_VXI11_ABORT,

};
